package com.mellowmist.servlet;
import com.mellowmist.model.User;
import com.mellowmist.dao.UserDAO;
import java.io.IOException;
import java.sql.SQLException;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;
@WebServlet("/AddUserServlet")
public class AddUserServlet extends HttpServlet {
   private static final long serialVersionUID = 1L;
   private UserDAO userDAO;
  
   public void init() {
       userDAO = new UserDAO();
   }
   protected void doPost(HttpServletRequest request, HttpServletResponse response)
           throws ServletException, IOException {
       try {
           // Get next available user ID (in a real application, this might be auto-generated by the database)
           int userId = getNextUserId();
          
           // Get parameters from form
           String username = request.getParameter("username");
           String password = request.getParameter("password");
           String email = request.getParameter("email");
           String role = request.getParameter("role");
           String status = request.getParameter("status");
          
           // Create new user object
           User user = new User(userId, username, password, email, role, status);
          
           // Add user to database
           boolean success = userDAO.addUser(user);
          
           // Store message in session instead of request
           HttpSession session = request.getSession();
           if (success) {
               session.setAttribute("message", "User added successfully");
               session.setAttribute("messageType", "success");
           } else {
               session.setAttribute("message", "Failed to add user");
               session.setAttribute("messageType", "error");
           }
          
           // Redirect back to user management page
           response.sendRedirect("Users.jsp");
          
       } catch (SQLException e) {
           HttpSession session = request.getSession();
           session.setAttribute("message", "Database error: " + e.getMessage());
           session.setAttribute("messageType", "error");
           response.sendRedirect("Users.jsp");
       } catch (Exception e) {
           HttpSession session = request.getSession();
           session.setAttribute("message", "Error: " + e.getMessage());
           session.setAttribute("messageType", "error");
           response.sendRedirect("Users.jsp");
       }
   }
  
   private int getNextUserId() throws SQLException {
       // A simple method to get the next available user ID
       // In a real application, this might be auto-generated by the database
       java.util.List<User> users = userDAO.getAllUsers();
      
       int maxId = 0;
       for (User user : users) {
           if (user.getId() > maxId) {
               maxId = user.getId();
           }
       }
      
       return maxId + 1;
   }
}

